# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: It's All About Me!
author: 
  fullname: Shantan Krovvidi
  email: shantank@gmail.com
  github_username:  shantank03
description: The Liberal Jekyll Theme
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shantank03.github.io" # the base hostname & protocol for your site
paginate: 5

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
